sudo: false
language: ruby
rvm:
  - 2.5.0
before_install: gem install bundler -v 1.16.1

bundler_args: --without production

services:
  - postgresql

before_script:
  - psql -c 'create database rakuten_test;' -U postgres
